#!/usr/bin/env python3
"""Build the v2 MiniCPM5 SFT dataset: parameterised, execution-verified maths +
logic tool-calling at scale.

v1 shipped ~17 hand-written cases (plus exact copies of the sample test tasks,
which the Participant Guide forbids training on and which cannot help on the
unseen prompt variants the leaderboard actually scores). v2 generates hundreds
of randomised instances across the benchmark's task families. Every case is
executed while building: the observation is real stdout, and the final answer
is INTERPOLATED from the executed namespace - never hand-typed - so the
dataset itself embodies the discipline the agent needs.

Two rows per case (same contract as v1 / eval_tool_behavior.py):
  1. user prompt                       -> assistant emits one <tool_call>
  2. prompt + run_python result + ask  -> assistant emits the final answer
"""

from __future__ import annotations

import argparse
import contextlib
import io
import itertools
import json
import random
from fractions import Fraction
from pathlib import Path

# The tool turn is the JSON tool call MiniCPM5 was pretrained on. A fenced-code
# alternative was tried to dodge GGUF's </tool_call> mangling but REGRESSED the
# 1B LoRA (syntax errors, repeat-loop degeneration even at F16), so JSON stays;
# the mangled closing tag is handled by the runtime's balanced-brace parser.
SYSTEM = """You are yassai-local, a small local specialist for math and logic tasks.
Use run_python for arithmetic, percentages, schedules, projections, combinatorics, and constraint checks.
Never do these calculations in your head.
When a tool is needed, respond with exactly one tool call and no prose:
<tool_call>{"name":"run_python","arguments":{"code":"..."}}</tool_call>
The Python must compute from named variables and print concise final values.
After receiving a run_python result, return only the final answer requested by the user."""

FIRST_NAMES = ["Alice", "Ben", "Carla", "Dmitri", "Elena", "Farid", "Grace", "Hugo", "Iris", "Jonas",
               "Kira", "Leo", "Mona", "Nils", "Olga", "Pablo", "Quinn", "Rosa", "Sam", "Tessa",
               "Umar", "Vera", "Wes", "Xena", "Yusuf", "Zoe", "Priya", "Liam", "Emma", "Noah"]


def compact_json(obj: object) -> str:
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def tool_call(code: str) -> str:
    return "<tool_call>" + compact_json({"name": "run_python", "arguments": {"code": code.strip()}}) + "</tool_call>"


def rows(prompt: str, code: str, answer: str) -> list[dict]:
    code = code.strip()
    buf = io.StringIO()
    ns: dict[str, object] = {}
    with contextlib.redirect_stdout(buf):
        exec(code, ns, ns)  # noqa: S102 - generated by us, verified here
    observation = buf.getvalue().strip()
    assert observation, f"code produced no output:\n{code}"
    after = f"{prompt.strip()}\n\nrun_python result:\n{observation}\n\nReturn the final answer only."
    return [
        {"messages": [{"role": "system", "content": SYSTEM},
                      {"role": "user", "content": prompt.strip()},
                      {"role": "assistant", "content": tool_call(code)}]},
        {"messages": [{"role": "system", "content": SYSTEM},
                      {"role": "user", "content": after},
                      {"role": "assistant", "content": answer.strip()}]},
    ]


# ------------------------------------------------------------------ maths families


def fam_warehouse(rng: random.Random) -> list[dict]:
    start = rng.choice(range(1200, 8001, 200))
    pct = rng.choice([15, 20, 25, 30, 35, 40, 45, 55, 60])
    restock = rng.choice(range(300, 1501, 50))
    after1 = start * (100 - pct) // 100
    assert start * (100 - pct) % 100 == 0
    sold3 = rng.choice(range(200, min(after1 + restock - 100, 2500), 20))
    remaining = after1 + restock - sold3
    site = rng.choice(["warehouse", "distribution centre", "depot", "fulfilment centre"])
    prompt = (f"A {site} starts with {start:,} units. In Q1 it sells {pct}% of stock. In Q2 it restocks "
              f"{restock} units. In Q3 it sells {sold3} units. How many units remain at the end of Q3?")
    code = (f"start = {start}\npct = {pct}\nafter_q1 = start * (100 - pct) // 100\n"
            f"after_q2 = after_q1 + {restock}\nremaining = after_q2 - {sold3}\nprint(remaining)")
    return rows(prompt, code, f"{remaining} units")


def fam_recipe(rng: random.Random) -> list[dict]:
    while True:
        num, den = rng.choice([(1, 2), (1, 4), (3, 4), (2, 3), (3, 5), (5, 8), (2, 5), (7, 8)])
        base = rng.choice([6, 8, 10, 12, 15, 16, 20, 24])
        target = rng.choice([9, 14, 18, 21, 25, 26, 28, 30, 32, 36, 40])
        needed = Fraction(num, den) * Fraction(target, base)
        if needed == 1 or needed.denominator == 1 or 10_000 % needed.denominator:
            continue
        price = rng.choice([1.2, 1.5, 1.6, 1.8, 2.0, 2.4, 2.5, 3.2, 4.0])
        cost = float(needed) * price
        if abs(cost - round(cost, 2)) > 1e-9:
            continue
        break
    ing, item = rng.choice([("sugar", "cookies"), ("flour", "muffins"), ("butter", "scones"),
                            ("cocoa", "brownies"), ("oats", "flapjacks")])
    prompt = (f"A recipe requires {num}/{den} cup of {ing} for {base} {item}. How much {ing} is needed "
              f"for {target} {item}? If {ing} costs ${price:.2f} per cup, what is the total cost of "
              f"{ing} for {target} {item}?")
    code = (f"from fractions import Fraction\nneeded = Fraction({num}, {den}) * Fraction({target}, {base})\n"
            f"cost = float(needed) * {price}\nprint(f'{{float(needed):g}} cups')\nprint(f'${{cost:.2f}}')")
    return rows(prompt, code, f"{float(needed):g} cups of {ing}; total cost ${cost:.2f}.")


def fam_trains(rng: random.Random) -> list[dict]:
    while True:
        v_a = rng.choice(range(60, 121, 5))
        v_b = rng.choice(range(60, 121, 5))
        gap_min = rng.choice([60, 75, 90, 105, 120])
        dep_a_h, dep_a_m = rng.choice([(6, 0), (6, 45), (7, 0), (7, 30), (8, 0), (8, 15), (9, 0)])
        dep_b_total = dep_a_h * 60 + dep_a_m + gap_min
        head_h = gap_min / 60
        dist = rng.choice(range(300, 651, 10))
        covered = v_a * head_h
        remaining = dist - covered
        if remaining <= 0:
            continue
        secs = remaining * 3600 / (v_a + v_b)
        if abs(secs - round(secs)) > 1e-9:
            continue
        secs = round(secs)
        from_a = v_a * (head_h + secs / 3600)
        if abs(from_a - round(from_a, 2)) > 1e-9:
            continue
        break
    meet_total = dep_b_total * 60 + secs
    mh, rem = divmod(meet_total, 3600)
    mm, ms = divmod(rem, 60)
    meet = f"{mh:02d}:{mm:02d}:{ms:02d}" if ms else f"{mh:02d}:{mm:02d}"
    dep_a = f"{dep_a_h:02d}:{dep_a_m:02d}"
    dep_b = f"{dep_b_total // 60:02d}:{dep_b_total % 60:02d}"
    prompt = (f"A train leaves City A at {dep_a} travelling toward City B at {v_a} km/h. A second train "
              f"leaves City B at {dep_b} travelling toward City A at {v_b} km/h. The distance between "
              f"the cities is {dist} km. At what time do the trains meet, and how far from City A is "
              f"the meeting point?")
    code = (f"from datetime import datetime, timedelta\ndistance = {dist}\nv_a = {v_a}\nv_b = {v_b}\n"
            f"start_a = datetime(2000, 1, 1, {dep_a_h}, {dep_a_m})\n"
            f"start_b = datetime(2000, 1, 1, {dep_b_total // 60}, {dep_b_total % 60})\n"
            f"head_h = (start_b - start_a).total_seconds() / 3600\n"
            f"remaining = distance - v_a * head_h\nafter_b_h = remaining / (v_a + v_b)\n"
            f"meet = start_b + timedelta(hours=after_b_h)\nfrom_a = v_a * (head_h + after_b_h)\n"
            f"assert abs(from_a / v_a - (head_h + after_b_h)) < 1e-9\n"
            f"fmt = '%H:%M:%S' if meet.second else '%H:%M'\n"
            f"print(meet.strftime(fmt))\nprint(f'{{from_a:g}} km from City A')")
    return rows(prompt, code, f"They meet at {meet}, {from_a:g} km from City A.")


def fam_revenue(rng: random.Random) -> list[dict]:
    half = rng.choice([["Jan", "Feb", "Mar", "Apr", "May", "Jun"], ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]])
    nxt = {"Jun": "Jul", "Dec": "Jan"}[half[-1]]
    base = rng.choice(range(80, 260, 10)) * 1000
    figures = [base]
    for _ in range(5):
        figures.append(int(figures[-1] * (1 + rng.choice([-8, -6, -4, -3, -2, 2, 3, 4, 6, 8, 10, 12]) / 100)))
    avg = sum(figures) / len(figures)
    rates, declines = [], []
    for i in range(1, 6):
        r = (figures[i] - figures[i - 1]) / figures[i - 1] * 100
        rates.append((half[i], r))
        if figures[i] < figures[i - 1]:
            declines.append(half[i])
    proj = figures[-1] * (1 + sum(r for _, r in rates[-3:]) / 3 / 100)
    figs_txt = " | ".join(f"{m} ${v:,}" for m, v in zip(half, figures))
    growth_txt = ", ".join(f"{m} {r:.1f}%" for m, r in rates)
    prompt = (f"Monthly revenue figures: {figs_txt}.\n\nCalculate all of the following:\n"
              f"1. Average monthly revenue across all six months.\n"
              f"2. Month-over-month growth rate for each month from {half[1]} onwards (as a percentage, "
              f"rounded to one decimal place).\n3. Which months saw a revenue decline?\n"
              f"4. Projected {nxt} revenue using the average of the last three months' growth rates.")
    code = (f"months = {half!r}\nrev = {figures!r}\navg = sum(rev) / len(rev)\n"
            f"rates = []\ndeclines = []\n"
            f"for i in range(1, len(rev)):\n"
            f"    r = (rev[i] - rev[i - 1]) / rev[i - 1] * 100\n"
            f"    rates.append((months[i], r))\n"
            f"    if rev[i] < rev[i - 1]:\n        declines.append(months[i])\n"
            f"last3 = [r for _, r in rates[-3:]]\nassert len(last3) == 3\n"
            f"proj = rev[-1] * (1 + sum(last3) / 3 / 100)\n"
            f"print(f'average=${{avg:,.2f}}')\n"
            f"print('growth=' + ', '.join(f'{{m}} {{r:.1f}}%' for m, r in rates))\n"
            f"print('declines=' + (', '.join(declines) or 'none'))\n"
            f"print(f'proj=${{proj:,.2f}}')")
    answer = (f"1. Average monthly revenue: ${avg:,.2f}. 2. Growth: {growth_txt}. "
              f"3. Declines: {', '.join(declines) if declines else 'none'}. "
              f"4. Projected {nxt} revenue: ${proj:,.2f}.")
    return rows(prompt, code, answer)


def fam_tank(rng: random.Random) -> list[dict]:
    start = rng.choice(range(300, 901, 20))
    d1, t1 = rng.choice(range(4, 13)), rng.choice(range(8, 21))
    f2, t2 = rng.choice(range(8, 19)), rng.choice(range(10, 25))
    d3, t3 = rng.choice(range(3, 10)), rng.choice(range(10, 25))
    final = start - d1 * t1 + f2 * t2 - d3 * t3
    if final <= 0:
        return fam_tank(rng)
    vessel = rng.choice(["tank", "reservoir", "cistern"])
    prompt = (f"A {vessel} starts with {start} litres. It drains at {d1} litres per minute for {t1} "
              f"minutes, is then refilled at {f2} litres per minute for {t2} minutes, then drains at "
              f"{d3} litres per minute for {t3} minutes. How many litres are in the {vessel} now?")
    code = (f"start = {start}\nafter_drain1 = start - {d1} * {t1}\n"
            f"after_fill = after_drain1 + {f2} * {t2}\nfinal = after_fill - {d3} * {t3}\nprint(final)")
    return rows(prompt, code, f"{final} litres")


def fam_pipes(rng: random.Random) -> list[dict]:
    a, b = rng.sample([3, 4, 5, 6, 8, 10, 12], 2)
    hours = 1 / (1 / a + 1 / b)
    prompt = (f"Pump A can fill a tank in {a} hours. Pump B can fill the same tank in {b} hours. "
              f"If both pumps run together, how many hours does filling take? Answer as a decimal "
              f"rounded to 2 decimal places.")
    code = (f"a = {a}\nb = {b}\nhours = 1 / (1 / a + 1 / b)\nprint(f'{{hours:.2f}}')")
    return rows(prompt, code, f"{hours:.2f} hours")


def fam_percent_chain(rng: random.Random) -> list[dict]:
    start = rng.choice(range(100, 901, 50))
    p1 = rng.choice([10, 15, 20, 25, 30])
    p2 = rng.choice([10, 15, 20, 25, 30])
    p3 = rng.choice([5, 8, 10, 12])
    final = start * (1 + p1 / 100) * (1 - p2 / 100) * (1 + p3 / 100)
    if abs(final - round(final, 2)) > 1e-9:
        return fam_percent_chain(rng)
    prompt = (f"A price is increased by {p1}%, then decreased by {p2}%, then increased by {p3}%. "
              f"If the original price was ${start}, what is the final price?")
    code = (f"start = {start}\nfinal = start * (1 + {p1}/100) * (1 - {p2}/100) * (1 + {p3}/100)\n"
            f"print(f'${{final:.2f}}')")
    return rows(prompt, code, f"${final:.2f}")


def fam_production(rng: random.Random) -> list[dict]:
    animal, unit = rng.choice([("ducks", "eggs"), ("hens", "eggs"), ("goats", "litres of milk")])
    per_day = rng.choice(range(14, 41, 2))
    eat = rng.choice(range(2, 7))
    use = rng.choice(range(3, 9))
    price = rng.choice([2, 3, 4, 5])
    sold = per_day - eat - use
    revenue = sold * price
    short_unit = "eggs" if unit == "eggs" else "litres"
    prompt = (f"Rina's {animal} produce {per_day} {unit} per day. She keeps {eat} for breakfast and uses "
              f"{use} for baking every day. She sells the rest for ${price} per {'egg' if unit == 'eggs' else 'litre'}. "
              f"How much money does she make each day? Give only the final numeric answer.")
    code = (f"produced = {per_day}\nkept = {eat}\nused = {use}\nsold = produced - kept - used\n"
            f"revenue = sold * {price}\nprint(revenue)")
    return rows(prompt, code, f"{revenue}")


# ------------------------------------------------------------------ logic families


FURRY = {"cat", "dog", "hamster", "rabbit"}


def fam_assignment(rng: random.Random) -> list[dict]:
    n = rng.choice([3, 4])
    people = rng.sample(FIRST_NAMES, n)
    domain_name, items = rng.choice([
        ("beverage", ["coffee", "tea", "water", "juice", "cocoa"]),
        ("pet", ["cat", "dog", "parrot", "hamster", "goldfish", "rabbit", "canary"]),
        ("instrument", ["guitar", "piano", "violin", "drums", "flute"]),
        ("sport", ["tennis", "rowing", "cycling", "boxing", "karate"]),
    ])
    items = rng.sample(items, n)
    solution = dict(zip(people, rng.sample(items, n)))

    clue_texts: list[str] = []
    preds = []
    fixed = rng.choice(people)
    clue_texts.append(f"{fixed} {'drinks' if domain_name == 'beverage' else 'has'} {solution[fixed]}.")
    preds.append(lambda a, p=fixed, it=solution[fixed]: a[p] == it)
    for p in people:
        if p == fixed:
            continue
        # semantic exclusion clue: 'allergic to fur' bans every furry item and
        # the CODE must encode that world knowledge as an explicit set.
        furry_here = [i for i in items if i in FURRY]
        if (domain_name == "pet" and solution[p] not in FURRY and furry_here
                and rng.random() < 0.5):
            clue_texts.append(f"{p} is allergic to fur.")
            preds.append(lambda a, p=p, banned=frozenset(furry_here): a[p] not in banned)
            continue
        wrongs = [i for i in items if i != solution[p]]
        k = rng.choice([1, 2]) if n == 4 else 1
        picked = rng.sample(wrongs, min(k, len(wrongs)))
        if len(picked) == 2:
            clue_texts.append(f"{p} has neither the {picked[0]} nor the {picked[1]}.")
        else:
            clue_texts.append(f"{p} does not have the {picked[0]}.")
        preds.append(lambda a, p=p, banned=frozenset(picked): a[p] not in banned)

    sols = [dict(zip(people, perm)) for perm in itertools.permutations(items)
            if all(pr(dict(zip(people, perm))) for pr in preds)]
    if len(sols) != 1 or sols[0] != solution:
        return fam_assignment(rng)  # resample until unique

    people_txt = ", ".join(people[:-1]) + f", and {people[-1]}"
    items_txt = ", ".join(items[:-1]) + f", or {items[-1]}"
    clues = "\n".join(f"{i + 1}. {c}" for i, c in enumerate(clue_texts))
    prompt = (f"{'Four' if n == 4 else 'Three'} friends — {people_txt} — each have a different "
              f"{domain_name}: {items_txt}. Use the following clues to determine who has what:\n{clues}\n"
              f"State each person's {domain_name}.")
    # rebuild the clue predicates as literal python conditions for the code string
    code_pre = ""
    code_conds = [f"d[{fixed!r}] == {solution[fixed]!r}"]
    for text in clue_texts[1:]:
        who = text.split()[0]
        if "allergic to fur" in text:
            code_pre = f"furred = {sorted(i for i in items if i in FURRY)!r}\n"
            code_conds.append(f"d[{who!r}] not in furred")
            continue
        banned = [i for i in items if f"the {i}" in text]
        if len(banned) == 2:
            code_conds.append(f"d[{who!r}] not in ({banned[0]!r}, {banned[1]!r})")
        else:
            code_conds.append(f"d[{who!r}] != {banned[0]!r}")
    cond_expr = " and ".join(code_conds)
    code = (f"import itertools\npeople = {people!r}\nitems = {items!r}\n{code_pre}sols = []\n"
            f"for perm in itertools.permutations(items):\n"
            f"    d = dict(zip(people, perm))\n"
            f"    if {cond_expr}:\n        sols.append(d)\n"
            f"assert len(sols) == 1\nd = sols[0]\n"
            f"print('; '.join(f'{{p}}: {{d[p]}}' for p in people))")
    answer = "; ".join(f"{p}: {solution[p]}" for p in people) + "."
    return rows(prompt, code, answer)


def fam_seating(rng: random.Random) -> list[dict]:
    people = rng.sample(FIRST_NAMES, 5)
    order = people[:]
    rng.shuffle(order)
    first, last = order[0], order[4]
    # adjacent pair clue from the true order
    idx = rng.choice([1, 2])
    left_p, right_p = order[idx], order[idx + 1]
    # non-adjacent clue: pick someone genuinely not next to `last`
    non_adj_candidates = [p for p in order[1:4] if abs(order.index(p) - 4) > 1]
    if not non_adj_candidates:
        return fam_seating(rng)
    loner = rng.choice(non_adj_candidates)

    sols = []
    for perm in itertools.permutations(people):
        if perm[0] != first or perm[4] != last:
            continue
        li, ri = perm.index(left_p), perm.index(right_p)
        if ri - li != 1:
            continue
        if abs(perm.index(loner) - perm.index(last)) == 1:
            continue
        sols.append(perm)
    if len(sols) != 1 or list(sols[0]) != order:
        return fam_seating(rng)

    people_txt = ", ".join(people[:-1]) + f", and {people[-1]}"
    prompt = (f"Five colleagues — {people_txt} — sit in five seats numbered 1 to 5 in a row (seat 1 is "
              f"the far left). {first} sits in seat 1. {last} sits in seat 5. {left_p} sits immediately "
              f"to the left of {right_p}. {loner} does not sit next to {last}. "
              f"What is the seating order from seat 1 to seat 5?")
    code = (f"import itertools\npeople = {people!r}\nsols = []\n"
            f"for perm in itertools.permutations(people):\n"
            f"    if perm[0] != {first!r} or perm[4] != {last!r}:\n        continue\n"
            f"    if perm.index({right_p!r}) - perm.index({left_p!r}) != 1:\n        continue\n"
            f"    if abs(perm.index({loner!r}) - perm.index({last!r})) == 1:\n        continue\n"
            f"    sols.append(perm)\n"
            f"assert len(sols) == 1\nprint(', '.join(sols[0]))")
    return rows(prompt, code, ", ".join(order) + ".")


def fam_eval_code(rng: random.Random) -> list[dict]:
    """'What does this evaluate to' semantics gotchas: the tool call RUNS the
    snippet and the final answer states the real values plus the mechanism."""
    kind = rng.choice(["late_binding", "mutable_default", "generator", "aliasing", "float_repr"])
    if kind == "late_binding":
        lo = rng.choice([1, 2, 3])
        hi = lo + 3
        arg = rng.choice([10, 20, 100])
        op, opname = rng.choice([("+", "x + i"), ("*", "x * i")])
        snippet = (f"def make_fns():\n    return [lambda x: x {op} i for i in range({lo}, {hi})]\n\n"
                   f"fns = make_fns()\nresults = [f({arg}) for f in fns]")
        mechanism = (f"the lambdas close over the loop variable i by reference (late binding), and i is "
                     f"{hi - 1} for all of them once the comprehension finishes")
        show = ["results"]
    elif kind == "mutable_default":
        a, b = rng.sample(range(1, 9), 2)
        snippet = (f"def add_item(item, box=[]):\n    box.append(item)\n    return box\n\n"
                   f"first = add_item({a})\nsecond = add_item({b})")
        mechanism = ("default argument values are evaluated once at definition time, so every call "
                     "without box shares the same mutable list")
        show = ["first", "second"]
    elif kind == "generator":
        n = rng.choice([6, 8, 10])
        nums = list(range(1, n + 1))
        snippet = (f"nums = {nums}\nevens = (x for x in nums if x % 2 == 0)\n"
                   f"total1 = sum(evens)\ntotal2 = sum(evens)")
        mechanism = "the generator is exhausted by the first sum(), so the second sum() sees nothing"
        show = ["total1", "total2"]
    elif kind == "aliasing":
        base = rng.sample(range(1, 20), 3)
        extra = rng.choice(range(20, 40))
        snippet = (f"a = {base}\nb = a\nb.append({extra})\nlength_a = len(a)\nsame = a is b")
        mechanism = "b = a binds a second name to the SAME list object, so mutating b mutates a"
        show = ["length_a", "same"]
    else:  # float_repr
        x, y = rng.choice([(0.1, 0.2), (0.1, 0.7), (0.2, 0.4)])
        target = round(x + y, 1)
        snippet = (f"total = {x} + {y}\nexact = total == {target}")
        mechanism = (f"binary floating point cannot represent {x} and {y} exactly, so their sum is not "
                     f"exactly {target}")
        show = ["exact", "total"]

    ns: dict[str, object] = {}
    exec(snippet, ns, ns)  # noqa: S102
    values = {k: ns[k] for k in show}
    names = " and ".join(f"`{k}`" for k in show)
    prompt = (f"What {'does' if len(show) == 1 else 'do'} {names} evaluate to, and why, given this "
              f"code?\n\n{snippet}")
    code = snippet + "\n" + "\n".join(f"print({k!r}, '=', repr({k}))" for k in show)
    answer = "; ".join(f"{k} = {values[k]!r}" for k in show) + f" - {mechanism}."
    return rows(prompt, code, answer)


def fam_weights(rng: random.Random) -> list[dict]:
    """Boxes with pairwise sum/diff constraints (the author's adversarial shape)."""
    boxes = ["P", "Q", "R", "S", "T"]
    weights = [2, 4, 6, 8, 10]
    solution = dict(zip(boxes, rng.sample(weights, 5)))
    pair = rng.sample(boxes, 2)
    pair_sum = solution[pair[0]] + solution[pair[1]]
    heavier = rng.sample([b for b in boxes if b not in pair], 2)
    if solution[heavier[0]] < solution[heavier[1]]:
        heavier.reverse()
    top = max(boxes, key=lambda b: solution[b])
    diff_pair = rng.sample(boxes, 2)
    diff = abs(solution[diff_pair[0]] - solution[diff_pair[1]])

    conds = [
        (f"{pair[0]} and {pair[1]} together weigh {pair_sum} kg.",
         f"w['{pair[0]}'] + w['{pair[1]}'] == {pair_sum}"),
        (f"{heavier[0]} is heavier than {heavier[1]}.",
         f"w['{heavier[0]}'] > w['{heavier[1]}']"),
        (f"{top} is the heaviest box.",
         f"w['{top}'] == max(w.values())"),
        (f"{diff_pair[0]} and {diff_pair[1]} differ by exactly {diff} kg.",
         f"abs(w['{diff_pair[0]}'] - w['{diff_pair[1]}']) == {diff}"),
    ]
    sols = []
    for perm in itertools.permutations(weights):
        w = dict(zip(boxes, perm))
        if all(eval(c, {"w": w}) for _, c in conds):  # noqa: S307 - our own literals
            sols.append(w)
    if len(sols) != 1 or sols[0] != solution:
        return fam_weights(rng)
    clue_txt = " ".join(t for t, _ in conds)
    prompt = (f"Five boxes — P, Q, R, S, and T — contain weights of 2, 4, 6, 8, and 10 kg, one weight "
              f"per box. {clue_txt} What is the weight of each box?")
    cond_expr = " and ".join(c for _, c in conds)
    code = (f"import itertools\nboxes = {boxes!r}\nsols = []\n"
            f"for perm in itertools.permutations([2, 4, 6, 8, 10]):\n"
            f"    w = dict(zip(boxes, perm))\n"
            f"    if {cond_expr}:\n        sols.append(w)\n"
            f"assert len(sols) == 1\nw = sols[0]\n"
            f"print('; '.join(f'{{b}}: {{w[b]}} kg' for b in boxes))")
    answer = "; ".join(f"{b}: {solution[b]} kg" for b in boxes) + "."
    return rows(prompt, code, answer)


FAMILIES = [
    (fam_warehouse, 40), (fam_recipe, 40), (fam_trains, 40), (fam_revenue, 40),
    (fam_tank, 30), (fam_pipes, 20), (fam_percent_chain, 30), (fam_production, 25),
    (fam_assignment, 50), (fam_seating, 35), (fam_eval_code, 40), (fam_weights, 25),
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="finetune/minicpm5/data/minicpm5_yassai_v2.jsonl")
    ap.add_argument("--seed", type=int, default=20260710)
    args = ap.parse_args()
    rng = random.Random(args.seed)
    out: list[dict] = []
    seen_prompts: set[str] = set()
    for fam, count in FAMILIES:
        made = 0
        while made < count:
            pair = fam(rng)
            p = pair[0]["messages"][1]["content"]
            if p in seen_prompts:
                continue
            seen_prompts.add(p)
            out.extend(pair)
            made += 1
    # World-knowledge exclusion clues (allergic-to-fur) appear only when the
    # pet domain and solution alignment coincide, so they are rare in the mix -
    # and v2e3b still mis-encodes them at eval. Triplicate those cases so the
    # exclusion pattern carries real gradient weight.
    boosted: list[dict] = []
    for i in range(0, len(out), 2):
        pair = out[i:i + 2]
        boosted.extend(pair)
        if "allergic" in pair[0]["messages"][1]["content"]:
            boosted.extend(pair)
            boosted.extend(pair)
    out = boosted
    path = Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in out:
            f.write(compact_json(r) + "\n")
    print(f"wrote {len(out)} rows ({len(out) // 2} cases) to {path}")


if __name__ == "__main__":
    main()
